name: Build and Test (No Deploy)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build frontend
        run: |
          cd frontend
          yarn install
          yarn build
          echo "✅ Frontend build successful!"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          echo "✅ Backend dependencies installed!"

      - name: Test backend startup
        run: |
          cd backend
          python -c "import main; print('✅ Backend imports successfully!')"

      - name: Create deployment package
        run: |
          mkdir -p deployment-test
          cp -r backend/* deployment-test/
          mkdir -p deployment-test/frontend
          cp -r frontend/dist deployment-test/frontend/
          cp startup.sh deployment-test/
          cp startup.py deployment-test/
          cp web.config deployment-test/ || echo "web.config not found, skipping"
          echo "✅ Deployment package created!"
          ls -la deployment-test/
          echo "Frontend structure:"
          ls -la deployment-test/frontend/

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: deployment-package
          path: deployment-test/
          retention-days: 1