# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - SC-TO-CODE-BACKEND

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js for frontend
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build frontend
        run: |
          cd frontend
          yarn install
          yarn build

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install backend dependencies
        run: pip install -r backend/requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Create deployment package
        run: |
          echo "📦 Creating full-stack deployment package..."

          # Create deployment structure
          mkdir -p deployment-package

          # Copy backend files (all Python files to root for Azure)
          echo "📂 Copying backend files..."
          cp -r backend/* deployment-package/

          # Copy frontend build
          echo "📂 Copying frontend build..."
          if [ -d "frontend/dist" ]; then
            mkdir -p deployment-package/frontend
            cp -r frontend/dist deployment-package/frontend/
            echo "✅ Frontend build copied"
          else
            echo "⚠️ Frontend dist not found, skipping"
          fi

          # Copy deployment scripts
          echo "📂 Copying deployment scripts..."
          cp startup.sh deployment-package/ || echo "startup.sh not found"
          cp startup.py deployment-package/ || echo "startup.py not found"
          cp web.config deployment-package/ || echo "web.config not found"

          # Copy requirements.txt to root (Azure expects it there)
          cp backend/requirements.txt deployment-package/requirements.txt

          # Verify structure
          echo "📊 Deployment package structure:"
          ls -la deployment-package/
          echo "📊 Frontend structure (if exists):"
          ls -la deployment-package/frontend/ || echo "No frontend directory"

          echo "✅ Full-stack deployment package created!"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: deployment-package/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'SC-TO-CODE-BACKEND'
          slot-name: 'Production'
          startup-command: 'pip install -r requirements.txt && python -m uvicorn main:app --host 0.0.0.0 --port 8000'